// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "ulog-backend/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	articleGroup := r.Group("/article")
	articleGroup.GET(".")
	articleGroup.GET("/:id")
	articleGroup.GET("/:id/info", handler.GetArticleInfoById)
	articleGroup.GET("/category")
	articleGroup.POST("/:id/like")
	articleGroup.POST(".")
	articleGroup.DELETE("/:id")

	tagGroup := r.Group("/tag")
	tagGroup.GET(".")
	tagGroup.POST(".")
	tagGroup.DELETE("/:id")

	userGroup := r.Group("/user")
	userGroup.GET("/user/:name")
	userGroup.GET("/login/passkey")
	userGroup.GET("/register/passkey")
	userGroup.POST("/user/login/:method")
	userGroup.POST("/user/register/:method")
	userGroup.POST("/user/forget")
	userGroup.POST("/user/logout")
	userGroup.DELETE("/user/:id")
}
