// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string    `gorm:"column:name;not null" json:"name"`
	Articles []Article `gorm:"many2many:articles_tags" json:"articles,omitempty"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
