// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID     string     `gorm:"column:uuid;not null" json:"uuid"`
	Name     string     `gorm:"column:name;not null" json:"name"`
	Password *string    `gorm:"column:password" json:"-"`
	Avatar   *string    `gorm:"column:avatar" json:"avatar"`
	Birthday *time.Time `gorm:"column:birthday" json:"birthday,omitempty"`
	Email    *string    `gorm:"column:email" json:"email,omitempty"`
	Articles []Article  `gorm:"many2many:articles_authors" json:"articles,omitempty"`
	Likes    []Article  `gorm:"many2many:articles_likes" json:"likes,omitempty"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
